name = "Floodlight"
license = "ISC"
description = "Minimal, fast, no-JavaScript dark theme with a single neon accent."
homepage = "https://huhn.dev"
tags = ["blog", "minimal", "dark"]
features = ["blog"]
min_version = "0.110"

[author]
  name = "Julian Huhn"
  homepage = "https://huhn.dev"
